import Image from 'next/image'
import { ReactElement } from 'react'

import type { Metadata } from 'next'
import { ThemeController } from '@/components/custom/ThemeController'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Home = () => {
  return <></>
}

Home.getLayout = function RootLayout(page: ReactElement) {
  return (
    <html lang="en" data-theme="nord">
      <body className="grid max-w-7xl">{page}</body>
    </html>
  )
}

export default Home
