import { createPennyService } from '../../app/penny'
import { Metadata } from 'next'
import { FormEvent, ReactElement } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const handleLogin = (e: FormEvent) => {
  e.preventDefault()

  const penny = createPennyService()
  if (e.target?.email.value && e.target?.password.value) {
    console.log(e.target?.email.value, e.target?.password.value)
    penny
      .signIn(e.target?.email.value, e.target?.password.value)
      .then((data) => {
        console.log(data)
      })
      .catch((error) => console.log(error))
  }
  //penny.signIn()
}

const SignIn = () => {
  return (
    <>
      <form onSubmit={handleLogin}>
        <fieldset className="fieldset bg-base-200 border-base-300 rounded-box w-xs border p-4">
          <legend className="fieldset-legend">Login</legend>

          <label className="label">Email</label>
          <input
            type="email"
            className="input"
            name="email"
            placeholder="Email"
          />

          <label className="label">Password</label>
          <input
            type="password"
            className="input"
            name="password"
            placeholder="Password"
          />

          <button className="btn btn-neutral mt-4">Login</button>
        </fieldset>
      </form>
    </>
  )
}

SignIn.getLayout = function SignInLayout(page: ReactElement) {
  return <>{page}</>
}

export default SignIn
